---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications-media-common
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/applications/media/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
