---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  # releaseName: pihole
  chart:
    spec:
      chart: pihole
      version: 2.19.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      interval: 5m
  values:
    DNS1: "10.0.3.24"
    adminPassword: ${PIHOLE_ADMINPASSWORD}
    serviceDns:
      type: LoadBalancer # was NodePort jjp
      loadBalancerIP: "10.0.3.209"
      annotations: # {}
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceDhcp:
      enabled: false # was true jjp
    virtualHost: "pihole-k8s.${NGINX_INGRESS_SECRET_DOMAIN}"
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-ceph-pvc
    ingress:
      enabled: true
      ingressClassName: "nginx-internal"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - &host "pihole-k8s.${NGINX_INGRESS_SECRET_DOMAIN}"
      tls:
        - secretName: tls.pihole
          hosts:
            - *host
