---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage-minio-app
  namespace: flux-system
spec:
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/storage/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
