---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-networking-traefik-app-crds-install
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: traefik-git-crds
