---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-kube-prometheus-stack-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/infrastructure/cluster/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
