apiVersion: v1
kind: Secret
metadata:
    name: grafana-restic-secret
    namespace: grafana
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:O2Hwt6wKb7RmiBNlYm2S25fUftm+4TfYmzRJnwq07iGt0/6yluu7DgBRcqqVEuqCpUP4bBw4HzyA,iv:oUE4VZLqQ0KARFvuaavvoJxoNeLjHh6DBSgDRq2H60E=,tag:DoVt3oDSStLCImmBZtBxTQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:L8hgNiRvIGsA29KL0dFTahoLTnVzLn7/YSY=,iv:ubnJIOkSwQaO5A+uJKh1G6x3UHO+q8M0NDzjYRenUv8=,tag:lUi4T1aPs5Xa2W4EkMzL8g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rs/IAhE=,iv:APWbirl1kTHGLuNueVPjOuozzoW73PDVpF7unQIKrNM=,tag:KGJ6rvxYVN2Bge+reHvA4g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kWHqd1Qq9MHZgw==,iv:tH7s6QP8l159SJcbDpGTs6LGf/G6IA0W3x0QTGZUJrw=,tag:dfSaWKoauP5tJLD1RY1+Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tatwwrxettyutu5zz3dmt349lqzjqfp8eheydzm76rqmqr5fu4usuj2cv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WWhqMnpvajhCNTlhUUE2
            citLSEl1VVEwQkc1ZnJsSDVBMmo5d2hFbXp3CmdmQnV4eWs1aDhsd1BpYWNtdGlY
            dkJsUTY4RWRhYkpVV3FQbXo2ZlVWdFUKLS0tIDNKVXBpWUJBVExRbjNFekJkRVli
            RDg1VXFjdVlTdk1rMjBPQ3hZWkQ3OFUKPhmJbHqOvgqXQ8KBvpBzftidjoFVNW4L
            6DQAkswn5Jbi4+MT1qAala8uI5gGN8ejG38nc1E4rTiVyF6eqXiHSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T18:26:48Z"
    mac: ENC[AES256_GCM,data:pwo8UcR1c5vc3umIeoN6WvL2H1XnjN+3znitcxEhsgVO/lMAgBSCEKuXNYtjlpD61ThvOaZittTjRN7S3QCODtksBv7Plpq/tE7lBxYyW5rpnhESWTgAxMLXZ8sHhJ3mGn630nwnjrvEFBl2fJMxPUw81+PQijPnf5xUVkHvwTo=,iv:qn5nguv2gsuYZ9jEoOYIWlkXretu48tgKi2tvaxLnTQ=,tag:5G12EPLrCGbaw6s+u94Q3g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(^trusted|^secrets|^trustdinfo|^cluster|.[pP]assword|crt|key|^data$|^stringData))
    version: 3.7.3
