apiVersion: v1
kind: Secret
metadata:
    name: grafana-restic-secret
    namespace: grafana
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:bMsjSMv2u47aHw/H2zVDGWJBuEwz9qOMlqldDfx+xaGwhNRczXFuCx0=,iv:bj6q3vlbjvTVxhY2nJUgOkRK5yWBCCvfnFR+tYSNop0=,tag:8M8D9Bgog1RSsQzN/+w6QA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:L8hgNiRvIGsA29KL0dFTahoLTnVzLn7/YSY=,iv:ubnJIOkSwQaO5A+uJKh1G6x3UHO+q8M0NDzjYRenUv8=,tag:lUi4T1aPs5Xa2W4EkMzL8g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rs/IAhE=,iv:APWbirl1kTHGLuNueVPjOuozzoW73PDVpF7unQIKrNM=,tag:KGJ6rvxYVN2Bge+reHvA4g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kWHqd1Qq9MHZgw==,iv:tH7s6QP8l159SJcbDpGTs6LGf/G6IA0W3x0QTGZUJrw=,tag:dfSaWKoauP5tJLD1RY1+Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tatwwrxettyutu5zz3dmt349lqzjqfp8eheydzm76rqmqr5fu4usuj2cv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WWhqMnpvajhCNTlhUUE2
            citLSEl1VVEwQkc1ZnJsSDVBMmo5d2hFbXp3CmdmQnV4eWs1aDhsd1BpYWNtdGlY
            dkJsUTY4RWRhYkpVV3FQbXo2ZlVWdFUKLS0tIDNKVXBpWUJBVExRbjNFekJkRVli
            RDg1VXFjdVlTdk1rMjBPQ3hZWkQ3OFUKPhmJbHqOvgqXQ8KBvpBzftidjoFVNW4L
            6DQAkswn5Jbi4+MT1qAala8uI5gGN8ejG38nc1E4rTiVyF6eqXiHSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T18:17:08Z"
    mac: ENC[AES256_GCM,data:V0JOhxkvrl3N4CDzW9owaCt6IRXvARnAYY/YcgYhU8a2kCAgfECnr4hghkOEUrEmwGJu9lQMB/Sq2K1bt918w1t8hx8f2MceFyJuElK1BU6yorsfOyZik5yYvG/0EVYRCLUpAtD6kAUHKqL5D2vf8rmbZDH6OTr1SdIsqOS8Nfg=,iv:OUZPbrsyPtJdAUMbxTvK6ddwwZJA8oXaFlI1salXcYo=,tag:yjPrAv5OQa7hTZ5gXqLhLw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(^trusted|^secrets|^trustdinfo|^cluster|.[pP]assword|crt|key|^data$|^stringData))
    version: 3.7.3
