---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applications-netwroking-pihole-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/applications/networking/pihole/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
