apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
  namespace: frigate
data:
  config.yaml: |
    logger:
      default: info

    mqtt:
      host: emqx.emqx.svc.cluster.local
      topic_prefix: frigate
      user: <path:cluster-secrets:cluster-secrets#emqx-frigate-user>
      password: <path:cluster-secrets:cluster-secrets#emqx-frigate-password>

    database:
      path: /data/frigate.db

    detectors:
      coral:
        type: edgetpu
        device: pci

    objects:
      track:
        - person
        - dog
        - car
        - cat
        - bicycle
        - motorcycle

    go2rtc:
      streams:
        alley_main: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.52:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
        alley_sub: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.52:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
        backyard_main: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.50:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
        backyard_sub: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.50:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
        garage_main: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.100:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
        garage_sub: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.100:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
        front_porch_main: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.101:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
        front_porch_sub: rtsp://<path:cluster-secrets:cluster-secrets#frigate-camera-user>:<path:cluster-secrets:cluster-secrets#frigate-camera-password>@10.0.10.101:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2

    record:
      enabled: True
      sync_recordings: True
      retain:
        days: 5
        mode: all
      alerts:
        retain:
          days: 10
          mode: motion
      detections:
        retain:
          days: 10
          mode: motion

    snapshots:
      enabled: True

    model:
      path: plus://189e906f54c63dd708d4b869954c4f82

    detect:
      width: 640
      height: 480
      fps: 10

    cameras:
      alley:
        enabled: True
        live:
          stream_name: alley_main
        motion:
          mask:
            # ignore timestamp
            - 0.037,0.064,0.375,0.064,0.375,0.099,0.042,0.098
        ffmpeg:
          hwaccel_args: preset-vaapi
          inputs:
            - path: rtsp://localhost:8554/alley_sub
              roles:
                - detect
            - path: rtsp://localhost:8554/alley_main
              roles:
                - record

      front_porch:
        enabled: True
        live:
          stream_name: front_porch_main
        motion:
          mask:
            # ignore timestamp
            - 0.037,0.064,0.375,0.064,0.375,0.099,0.042,0.098
            # plants
            - 0.681,0.702,0.642,0.63,0.579,0.652,0.553,0.6,0.534,0.606,0.523,0.587,0.511,0.591,0.474,0.526,0.464,0.499,0.794,0.354
            - 0.331,0.55,0.451,0.701,0.253,0.795,0.22,0.862,0.184,0.906,0.144,0.927,0.154,0.979,0.002,0.954,0.011,0.699,0.069,0.671
        zones:
          south_lawn:
            coordinates: 0.588,0.424,0.509,0.276,0.709,0.236,0.789,0.333
          north_lawn_n:
            coordinates: 0.25,0.368,0.006,0.464,0.006,0.689,0.047,0.67,0.309,0.55
          north_lawn_s:
            coordinates: 0.504,0.28,0.395,0.318,0.467,0.47,0.581,0.427
          patio:
            coordinates: 0.761,0.955,0.644,0.672,0.404,0.742,0.27,0.894,0.355,0.988,0.624,0.992
          patio_entry:
            coordinates: 0.303,0.403,0.374,0.379,0.458,0.531,0.557,0.644,0.463,0.678,0.357,0.536
          sidewalk:
            coordinates: 0.004,0.356,0.007,0.434,0.175,0.36,0.367,0.293,0.558,0.237,0.704,0.212,0.754,0.256,0.757,0.194,0.708,0.138,0.664,0.13,0.651,0.173,0.532,0.184,0.314,0.23,0.131,0.297,0.074,0.323,0.037,0.343
            # objects:
            #   - person
        ffmpeg:
          hwaccel_args: preset-vaapi
          inputs:
            - path: rtsp://localhost:8554/front_porch_sub
              roles:
                - detect
            - path: rtsp://localhost:8554/front_porch_main
              roles:
                - record

      backyard:
        enabled: True
        live:
          stream_name: backyard_main
        motion:
          mask:
            # ignore tree moving and sun shade sails blowing in the wind
            - 0.928,0.735,0.868,0.742,0.759,0.754,0.734,0.658,0.763,0.583,0.672,0.502,0.627,0.383,0.624,0.295,0.663,0.246,0.683,0.195,0.232,0.044,0.041,0.024,0.041,0,1,0.002,0.999,0.533
            # ignore timestamp
            - 0.037,0.064,0.375,0.064,0.375,0.099,0.042,0.098
        objects:
          filters:
            cat:
              mask:
                # ignore rock that looks like a cat
                - 0.145,0.501,0.165,0.507,0.174,0.55,0.193,0.601,0.177,0.634,0.152,0.603,0.137,0.542
            dog:
              mask:
                # ignore rock that looks like a dog
                - 0.145,0.501,0.165,0.507,0.174,0.55,0.193,0.601,0.177,0.634,0.152,0.603,0.137,0.542
            car:
              mask:
                # there are no cars in the backyard
                - 0.007,0.06,0.23,0.023,0.581,0.051,0.798,0.174,0.927,0.363,0.904,0.616,0.912,0.903,0.919,0.99,0.005,0.992
        ffmpeg:
          hwaccel_args: preset-vaapi
          inputs:
            - path: rtsp://localhost:8554/backyard_sub
              roles:
                - detect
            - path: rtsp://localhost:8554/backyard_main
              roles:
                - record

      garage:
        enabled: True
        live:
          stream_name: garage_main
        motion:
          mask: # ignore timestamp
            - 0.037,0.064,0.375,0.064,0.375,0.099,0.042,0.098
        objects:
          filters:
            car:
              mask:
                # ignore parked car that has moving shadows on it
                - 0.212,0.005,0.093,0.178,0.302,0.869,0.483,0.849,0.64,0.745,0.811,0.174,0.736,0.088,0.713,0.005
            person:
              mask:
                # ignore shadows on ground that keep moving and look like a person
                - 0.336,1,0.375,0.71,0.277,0.536,0.067,0.614,0.133,0.841,0.213,1
        ffmpeg:
          hwaccel_args: preset-vaapi
          inputs:
            - path: rtsp://localhost:8554/garage_sub
              roles:
                - detect
            - path: rtsp://localhost:8554/garage_main
              roles:
                - record
