---
apiVersion: v1
kind: Namespace
metadata:
  name: joey

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jreplicaset
  namespace: joey
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - image: nginx
        name: web
        volumeMounts:
        - mountPath: "/tmp"
          name: temp-volume
      restartPolicy: Always
      volumes:
      - name: temp-volume
        persistentVolumeClaim:
          claimName: jpvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jpvc
  namespace: joey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: Service
metadata:
  name: jservice
  namespace: joey
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jingressroute
  namespace: joey
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("joey.piccola.us")
      kind: Rule
      services:
        - name: jservice
          port: 80
  tls:
    certResolver: letsencrypt
