version: '3'

tasks:

  terraform_apply:
    desc: Apply Terraform
    silent: true
    cmds:
      - terraform -chdir=terraform_proxmox apply

  set_k8s_context:
    desc: Set the k8s context to Talos
    silent: true
    cmds:
      - kubectl config set-context admin@talos

  install:gateway_api_crds:
    desc: Install Gateway API CRDs
    silent: true
    deps: [set_k8s_context]
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml


  install:cilium:
    desc: Install Cilium
    silent: true
    cmds:
      - |
        helm repo add cilium https://helm.cilium.io/
        helm repo update cilium
        cilium_helm_release=$(yq '.spec.sources[0].targetRevision' ./argocd/aoa_apps/apps/networking/cilium.yaml)
        helm template cilium cilium/cilium --version $cilium_helm_release --namespace kube-system --values ./argocd/aoa_apps/values/cilium.yaml | kubectl apply -f -

  install:argocd:
    desc: Install ArgoCD
    silent: true
    cmds:
      - |
        kubectl get namespace argocd >/dev/null 2>&1 || kubectl create namespace argocd
        kubectl config set-context --current --namespace=argocd
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update argo
        argo_helm_release=$(yq '.spec.sources[0].targetRevision' ./argocd/aoa_apps/apps/argocd.yaml)
        helm template argocd argo/argo-cd --version $argo_helm_release --namespace argocd --values ./argocd/aoa_apps/values/argocd.yaml | kubectl apply -f -

  stage:onepassword_secrets:
    desc: Stage OnePassword Secrets
    silent: true
    cmds:
      - |
        kubectl get namespace onepassword >/dev/null 2>&1 || kubectl create namespace onepassword
        onepass_creds_b64=$(op document get 'talos Credentials File' | base64)
        onepass_token=$(op item get 'talos Access Token Kubernetes operator' --format json --fields credential | jq -r .value)
        onepass_helm_release=connect-$(yq '.spec.source.targetRevision' argocd/aoa_infra/apps/onepassword.yaml)
        onepass_token=$onepass_token onepass_helm_release=$onepass_helm_release yq '.stringData.token = env(onepass_token), .metadata.labels."helm.sh/chart" = env(onepass_helm_release)' ./bootstrap/onepassword-token.yaml | kubectl apply -f -
        onepass_creds_b64=$onepass_creds_b64 onepass_helm_release=$onepass_helm_release yq '.stringData."1password-credentials.json" = env(onepass_creds_b64), .metadata.labels."helm.sh/chart" = env(onepass_helm_release)' ./bootstrap/op-credentials.yaml | kubectl apply -f -

  talos:genconfig:
    desc: Generate talos configs with talhelper
    silent: true
    dir: talos
    cmds:
      - talhelper genconfig

  talos:apply-config:
    desc: Apply generated talos configs
    silent: true
    env:
      TALOSCONFIG: talos/clusterconfig/talosconfig
    cmds:
      - talosctl apply-config --insecure -f talos/clusterconfig/talos-control-1.k8s.piccola.us.yaml -n control-1.k8s.piccola.us
      - talosctl apply-config --insecure -f talos/clusterconfig/talos-control-2.k8s.piccola.us.yaml -n control-2.k8s.piccola.us
      - talosctl apply-config --insecure -f talos/clusterconfig/talos-control-3.k8s.piccola.us.yaml -n control-3.k8s.piccola.us
      - talosctl apply-config --insecure -f talos/clusterconfig/talos-control-4.k8s.piccola.us.yaml -n control-4.k8s.piccola.us
      - talosctl apply-config --insecure -f talos/clusterconfig/talos-control-5.k8s.piccola.us.yaml -n control-5.k8s.piccola.us

  talos:bootstrap:
    desc: Bootstrap the talos cluster
    silent: true
    env:
      TALOSCONFIG: talos/clusterconfig/talosconfig
    cmds:
      - talosctl bootstrap -n control-1.k8s.piccola.us -e control-1.k8s.piccola.us

  talos:get-kubeconfig:
    desc: Get and merge the cluster kubeconfig (only required if you gen'd new talos secrets)
    silent: true
    env:
      TALOSCONFIG: talos/clusterconfig/talosconfig
    cmds:
      - talosctl kubeconfig --nodes control-1.k8s.piccola.us --endpoints control-1.k8s.piccola.us

  talos:reset-nodes:
    desc: Reset all talos nodes and reboot
    silent: true
    env:
      TALOSCONFIG: talos/clusterconfig/talosconfig
    cmds:
      - echo "you need uncomment this task's command for it to work"
      # - talosctl reset --reboot --graceful=false -n 10.0.5.201,10.0.5.202,10.0.5.203,10.0.5.204,10.0.5.205

  argocd:getadminsecret:
    desc: Get the ArgoCD initial admin secret
    silent: true
    cmds:
      - kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode; echo

  ha-codeserver:getpassword:
    desc: Get the HA code-server password
    silent: true
    cmds:
      - kubectl exec -n home-assistant -c codeserver $(kubectl get pod -n home-assistant -o jsonpath='{.items[0].metadata.name}') -- cat /home/coder/.config/code-server/config.yaml| grep '^password:' | awk '{print $2}'


  # argocd:login:
  #   desc: blah
  #   silent: true
  #   vars:
  #     PASSWORD:
  #       sh: task argocd:getadminsecret
  #   cmds:
  #     # - echo {{.PASSWORD}}
  #     - argocd login argocd-k8s.piccola.us:443 --username admin --password '{{.PASSWORD}}' --plaintext

  # talos:wipe-nvme:
  #   desc: Wipe nvme0n1 disks
  #   silent: false
  #   env:
  #     TALOSCONFIG: talos/clusterconfig/talosconfig
  #   cmds:
  #     - talosctl wipe disk nvme0n1 -n control-1.k8s.piccola.us
  #     - talosctl wipe disk nvme0n1 -n control-2.k8s.piccola.us
  #     - talosctl wipe disk nvme0n1 -n control-3.k8s.piccola.us
  #     - talosctl wipe disk nvme0n1 -n control-4.k8s.piccola.us
  #     - talosctl wipe disk nvme0n1 -n control-5.k8s.piccola.us
