---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${CEPH_DASHBOARD}`)
      kind: Rule
      services:
        - name: rook-ceph-mgr-dashboard
          port: 8443
  tls:
    certResolver: letsencrypt
