# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sonarr-config
#   namespace: sonarr
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-2
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
