# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: unifi-config
#   namespace: unifi-controller
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 2Gi
