# Possible values: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dyndns-objects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/joeypiccola/k8s_home.git
    path: argocd/aoa_apps/objects/dyndns
    targetRevision: main
  destination:
    name: in-cluster
    namespace: dyndns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
