---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-kyverno-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/infrastructure/cluster/kyverno/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-kyverno-policies
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/infrastructure/cluster/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
  dependsOn:
    - name: infrastructure-cluster-kyverno-app
