---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${NGINX_INGRESS_SECRET_DOMAIN/./-}"
  namespace: ingress-nginx
spec:
  secretName: "${NGINX_INGRESS_SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${NGINX_INGRESS_SECRET_DOMAIN}"
  dnsNames:
    - "${NGINX_INGRESS_SECRET_DOMAIN}"
    - "*.${NGINX_INGRESS_SECRET_DOMAIN}"
    - "*.${CLUSTER_NAME}.${NGINX_INGRESS_SECRET_DOMAIN}"
