apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:Dly+mw8=,iv:hEdeT7hXETHF1AgmbjtwBnGofgitCTYtJXY8tc4oXRw=,tag:xa5zj80BEYlv92ntr89tfA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:u2KAsAs=,iv:Kb7boFCF5pwvtGWD/GFDz0I56VsMsA35h/k7f1XUwz8=,tag:Wd0ZCPfaB/ywYjK81QhUVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tatwwrxettyutu5zz3dmt349lqzjqfp8eheydzm76rqmqr5fu4usuj2cv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ekduRFVNUWVIOHFUTWxi
            UkNQZ2o3Zk8yZ0sybnN1VXhpYitlcHA5TVR3Cmtwb1ZvTjUzdEh6MFJKMzNKcHM4
            MGF4UlVzdUM4ZmliendJNzdVd25MMHcKLS0tIGFuRnFzZ3JHWFRKMlg5Q0x1V2VR
            aWFMUElWemZHMW9CSSt6NUV1SFcxT2cKIj1VPyAGA8kV0JMy56WG+y5wo9/lVKL4
            YmIGcVMlLiFoxZjFybFOBV2GHyV9+COlFhH08ehh+n8pezPkm2foeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T20:40:34Z"
    mac: ENC[AES256_GCM,data:N2j1PhaJ9dwCIqkvICq8U3M/HjaNnv2lY/YgVdTGave+oUfINWl9q0jWB/D8vaUyDZ8Irp1hhaXCbcXwqxYQd6Wc0JqO3uWxIsPBm5zoCf3VG/mCLKBMqULKgSLiJpZaiPmC5/3Irn7c7CxXgBd/Pufs83asmkWeVqeR89MMRoU=,iv:K1v8Rnlc0XjHBa8PL0uJUEfp73o2NC6cYjbaGrF79hg=,tag:EXGCIMxP6qFxV7y8zv97SQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(^trusted|^secrets|^trustdinfo|^cluster|.[pP]assword|crt|key|^data$|^stringData))
    version: 3.7.3
