---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-credentials # this is the name of the k8s secret object
  namespace: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: credentials.json # this is the name of the data property on the k8s secret
      remoteRef:
        key: cluster-secrets # this is the title of the item in 1password
        property: cloudflared-credentialsjson # this is the name of the property on the 1password item
