---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-ceph-pvc
  namespace: sabnzbd
  # labels:
  #   kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: ceph-block
