---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-ceph-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: ceph-block
