---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  sourcePVC: sabnzbd-ceph-pvc
  trigger:
    schedule: "11 35 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: sabnzbd-restic-secret
    cacheCapacity: 8Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 14
