---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-networking-ingress-nginx-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/infrastructure/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
