kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: pvc-backup
  namespace: kasten-io
spec:
  comment: Policy to backup all resources daily.  Daily snapshot/backup
  frequency: "@daily"
  subFrequency:
    minutes:
      - 0
    hours:
      - 17
    weekdays:
      - 0
    days:
      - 1
    months:
      - 1
  retention:
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - pihole
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources:
            - resource: persistentvolumeclaims
              matchExpressions:
                - key: kasten.io/backup-volume
                  operator: In
                  values:
                    - enabled
          # excludeResources:
          #   - name: downloads-nfs-ebooks
          #     resource: persistentvolumeclaims
          #   - name: nextcloud-nfs-config
          #     resource: persistentvolumeclaims
          #   - name: audiobookshelf-nfs-audiobooks
          #     resource: persistentvolumeclaims
          #   - name: downloads-nfs-ebooks
          #     resource: persistentvolumeclaims
          #   - name: esphome-nfs-config
          #     resource: persistentvolumeclaims
          #   - name: audiobookshelf-nfs-audiobooks
          #     resource: persistentvolumeclaims
        profile:
          name: disaster-recovery
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@daily"
        profile:
          name: k10-disaster-recovery
          namespace: kasten-io

        exportData:
          enabled: true
      retention: {}
