---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.11.8
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  values:
    # crds:
    #   enabled: true <-- already default

    csi:
      # kubeletDirPath: /var/lib/kubelet <-- already default
      # enableCSIHostNetwork: true <-- already default
      pluginTolerations: # Array of tolerations in YAML format which will be added to CephCSI plugin DaemonSet
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"

    # monitoring: <-- defaults to false
    #   enabled: true

      # resources: <-- defaults
      #   limits:
      #     cpu: 500m
      #     memory: 512Mi
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi
