---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  # releaseName: pihole
  chart:
    spec:
      chart: pihole
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      interval: 5m
  values:
    adminPassword: ${PIHOLE_ADMINPASSWORD}
    serviceDns:
      type: LoadBalancer # was NodePort jjp
      loadBalancerIP: "10.0.3.209"
      annotations: # {}
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceDhcp:
      enabled: false # was true jjp
    virtualHost: ${PIHOLE_VIRTUALHOST}
