---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${PIHOLE_VIRTUALHOST}`)
      kind: Rule
      services:
        - name: pihole-web
          port: 80
  tls:
    certResolver: letsencrypt
