---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-metrics-server-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/infrastructure/cluster/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
