# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-state-metrics
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "100"
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   destination:
#     name: in-cluster
#     namespace: kube-state-metrics
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#   source:
#     chart: kube-state-metrics
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 5.30.0
#     helm:
#       releaseName: kube-state-metrics
#       valuesObject:
#         fullnameOverride: kube-state-metrics
#         prometheus:
#           monitor:
#             enabled: true
#             honorLabels: true
