apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: privileged
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.0.1
      helm:
        releaseName: frigate
        valuesObject:


          defaultPodOptions:
            nodeSelector:
              feature.node.kubernetes.io/pci-0880_1ac1_089a.present: "true"
          controllers:
            frigate:
              # pod:
              #   securityContext:
              #     privileged: true
              annotations:
                reloader.stakater.com/auto: "true"
              containers:
                app:
                  image:
                    repository: ghcr.io/blakeblackshear/frigate
                    tag: 0.15.1@sha256:c4e02d2c511847eebbda8e0e370b41c78e7b51247353de79340e06c3e95f11be
                  env:
                    TZ: America/Denver
                  # envFrom:
                  #   - secretRef:
                  #       name: frigate-secret
                  probes:
                    liveness: &probes
                      enabled: true
                      custom: true
                      spec:
                        httpGet:
                          path: /api/version
                          port: &port 5000
                        initialDelaySeconds: 0
                        periodSeconds: 10
                        timeoutSeconds: 1
                        failureThreshold: 3
                    readiness: *probes
                    startup:
                      enabled: false

                  resources:
                    requests:
                      gpu.intel.com/i915: "1"
                    limits:
                      gpu.intel.com/i915: "1"
          service:
            app:
              controller: frigate
              ports:
                http:
                  port: *port
                rtsp:
                  enabled: true
                  port: 8554
          route:
            main:
              parentRefs:
                - name: internal
                  namespace: gateway
                  # sectionName: https
              hostnames:
                - frigate-k8s.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 5000
                      name: frigate
                      namespace: frigate
                      weight: 1

          persistence:
            config:
              enabled: true
              existingClaim: frigate-data
              globalMounts:
                - path: /data
            config-file:
              type: configMap
              name: frigate-configmap
              globalMounts:
                - path: /config/config.yaml
                  subPath: config.yaml
                  readOnly: true
            # media:
            #   enabled: true
            #   type: nfs
            #   server: ds1515.ad.<path:cluster-secrets:cluster-secrets#domain>
            #   path: /frigate
            #   globalMounts:
            #     # take /mnt/storage/media/ and mount it to /media/frigate
            #     - path: /media/frigate
            #       # subPath: downloads
            cache:
              type: emptyDir
              medium: Memory
              sizeLimit: 4Gi
              globalMounts:
                - path: /dev/shm
            # coral:
            #   type: hostPath
            #   hostPath: /dev/apex_0
            #   hostPathType: CharDevice
