apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: privileged
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 3.7.3
      helm:
        releaseName: home-assistant
        valuesObject:
          defaultPodOptions:
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch

          controllers:
            home-assistant:
              pod:
                # hostNetwork: true
                # dnsPolicy: ClusterFirstWithHostNet
              containers:
                app:
                  image:
                    repository: ghcr.io/home-assistant/home-assistant
                    tag: 2025.3.2
                  env:
                    TZ: America/Denver
                  #   POSTGRES_HOST:
                  #     valueFrom:
                  #       secretKeyRef:
                  #         name: home-assistant-secret
                  #         key: INIT_POSTGRES_HOST
                  #   POSTGRES_DB:
                  #     valueFrom:
                  #       secretKeyRef:
                  #         name: home-assistant-secret
                  #         key: INIT_POSTGRES_DBNAME
                  # envFrom:
                  #   - secretRef:
                  #       name: home-assistant-secret
                  # resources:
                  #   requests:
                  #     cpu: 109m
                  #     memory: 588M



          service:
            app:
              controller: home-assistant
              ports:
                http:
                  port: 8123
            # app-2:
            #   controller: home-assistant
            #   type: LoadBalancer
            #   annotations:
            #     io.cilium/lb-ipam-ips: 10.0.5.225
            #   # externalTrafficPolicy: Cluster
            #   ports:
            #     http:
            #       port: 8123

          route:
            main:
              parentRefs:
                - name: internal
                  namespace: gateway
                  # sectionName: https
              hostnames:
                - ha-k8s.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 8123
                      name: home-assistant
                      namespace: home-assistant
                      weight: 1



          persistence:
            config:
              existingClaim: home-assistant-config
              globalMounts:
                - path: /config
