---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/networking/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #     kind: HelmRelease
  #     name: metallb
  #     namespace: networking

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/networking/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
