---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage-rook-ceph-operator
  namespace: flux-system
spec:
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/storage/rook-ceph/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage-rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-storage-rook-ceph-operator
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/storage/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
