---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 20.8.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
      - name: volume-permissions
        image: busybox:1.35
        command: ["sh", "-c", "touch /data/acme.json && chmod -Rv 600 /data/* && chown 65532:65532 /data/acme.json"]
        volumeMounts:
          - name: data
            mountPath: /data
    ingressRoute:
      dashboard:
        enabled: false
    env:
      - name: CF_DNS_API_TOKEN
        value: "${CF_DNS_API_TOKEN}"
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          certResolver: "letsencrypt"
    service:
      spec:
        loadBalancerIP: 10.0.3.208
    persistence:
        enabled: true
      existingClaim: "traefik"
    certResolvers:
      letsencrypt:
        email: ${LE_EMAIL}
        dnsChallenge:
          provider: cloudflare
          delayBeforeCheck: 30
          resolvers:
            - 1.1.1.1
            - 8.8.8.8
        storage: /data/acme.json
