---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-goldilocks-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/infrastructure/cluster/goldilocks/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
  dependsOn:
    - name: infrastructure-cluster-metrics-server-app
    - name: infrastructure-cluster-vpa-app
