---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  storageClassName: media-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/storage/media
    server: ${SECRET_NAS1}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  media-nfs
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName:  media-nfs
  resources:
    requests:
      storage: 1Mi
