---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications-home-automation-grafana-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/applications/home-automation/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
