---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-<path:cluster-secrets:cluster-secrets#domain>
  namespace: gateway
spec:
  dnsNames:
    - '*.<path:cluster-secrets:cluster-secrets#domain>'
    - '<path:cluster-secrets:cluster-secrets#domain>'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: cert-<path:cluster-secrets:cluster-secrets#domain>
