---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.0.5.209
  listeners:
    # - protocol: TLS
    #   port: 443
    #   name: unifi-tls
    #   hostname: "unifi-k8s.piccola.us"
    #   tls:
    #     mode: Passthrough
    #     # certificateRefs:
    #     #   - kind: Secret
    #     #     name: cert-piccola.us
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: '*.piccola.us'
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-piccola.us
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: 'piccola.us'
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-piccola.us
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: gateway
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.0.5.210
    - type: Hostname
      value: "external.piccola.us"
  infrastructure:
    annotations:
      # when using gateway-apis in cilium it also creates a service
      # with a different name and tries to take this IP.
      # the problem is the service created by cilium is not the one used by envoy.
      # therefore, the service is disabled https://tinyurl.com/3mt3upd5
      lbipam.cilium.io/ips: 10.0.5.210
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: '*.piccola.us'
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: '*.piccola.us'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-piccola.us
