---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
