---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-metrics-server
        namespace: flux-system
      interval: 5m
  values:
#     metrics:
#       enabled: true
    defaultArgs:
#       - --cert-dir=/tmp # default from chart
      - --kubelet-preferred-address-types=Hostname #InternalIP,ExternalIP,Hostname # default from chart
#       - --kubelet-use-node-status-port # default from chart
#       - --metric-resolution=15s # default from chart
#       - --kubelet-insecure-tls
#       # - --secure-port=4443 # not sure what this one does

# # todo(joey): re kubelet-insecure-tls, lots of talk here for how not to do this: https://github.com/kubernetes-sigs/metrics-server/issues/196
