---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-metrics-server
        namespace: flux-system
      interval: 5m
  values:
#     metrics:
#       enabled: true
    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=Hostname,InternalIP,ExternalIP
      - --kubelet-use-node-status-port
      - --metric-resolution=15s

# # todo(joey): re kubelet-insecure-tls, lots of talk here for how not to do this: https://github.com/kubernetes-sigs/metrics-server/issues/196
