---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-networking-traefik-app
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-networking-traefik-app-crds-install
    - name: infrastructure-networking-metallb-config
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/networking/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-networking-traefik-app-crds
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: infrastructure-networking-metallb-config
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/networking/traefik/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
