---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/networking/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
