apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: "tailscale"
      containers:
      - name: tailscale
        image: ghcr.io/tailscale/tailscale:latest
        # ports:
        # - containerPort: 41641
        #   protocol: UDP
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Denver"
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_EXTRA_ARGS
          value: "--advertise-exit-node --hostname=k8s-home"
        - name: TS_ROUTES
          value: "10.0.3.0/24"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
              optional: false
        livenessProbe:
          exec:
            command:
            - tailscale
            - --socket=/tmp/tailscaled.sock
            - status
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 24
        startupProbe:
          exec:
            command:
            - tailscale
            - --socket=/tmp/tailscaled.sock
            - status
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 1
        # command: ["/bin/sh"]
        # args:
        #   - -c
        #   - >-
        #       apk add curl; apk fix &&
        #       apk add curl &&
        #       curl https://raw.githubusercontent.com/tailscale/tailscale/cced414/docs/k8s/run.sh -O &&
        #       echo "starting" &&
        #       sh run.sh
