---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./namespace.yaml
  - ./role.yaml
  - ./rolebinding.yaml
  - ./secrets.sops.yaml
  - ./serviceaccount.yaml
