apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: tailscale-auth-key
    namespace: tailscale
stringData:
    AUTH_KEY: ENC[AES256_GCM,data:tz7EGV6JOCuLbRXQbQbO4i5dS/DOeyQC2QIpdx831LjeKROSC6N69C/fdQEYXvzcLKWaLVDb/Vg=,iv:shPefftYMw2ug/4kiAIRNz7zU/4ecQZVaoAVLiSfXxw=,tag:3XJVXr+sybmUVZSnM0r6jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tatwwrxettyutu5zz3dmt349lqzjqfp8eheydzm76rqmqr5fu4usuj2cv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNVdvc0c4a2tsQ09oeVRY
            RVI5QnFGZTBlaklpa2ljeEZyK1hBTzB2a3h3CmJRRUJMazdvcm5SN0JydHVZdWNq
            WEtkUzFyT1pkZEtRN1NSa3NZSWxrSTgKLS0tIEtnVmRJclR1aWZnRUtUdHlHOVhJ
            TVdRbC9Qb3ZOUVJiN3QwQjh1ZFVONW8KNpf/f05iTddFhp9fn4LY/F1nebEP6Yn8
            l54JFwCvbxL4IFZpssIvKqwStzzVWPfuT8oq4i/ZI2j3B+GZ2AWH4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T02:13:09Z"
    mac: ENC[AES256_GCM,data:aUhXXOgmJ11Q4F9hHZ+Bd8/QTFTvXDEqa5FQ6tUjzC87SBtMkaW9iGOwm+ecB9DuWaFu09b6P5w7dISzJvzY5i/HumJvSM7Nr+CbK4TPHuEHmXRtCNlxEBy4DcioNu39egePH2biDPO2frUgzoQEx3nmFSyViWdhqrcQt7jSRBA=,iv:Cdspwg6RFUr4SYO7Iphpz98kjfe+W/gAaMtiKo6MWI8=,tag:3xycfmnSjf2Pid/FB6bDuw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(^trusted|^secrets|^trustdinfo|^cluster|.[pP]assword|crt|key|^data$|^stringData))
    version: 3.7.3
