apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    AUTH_KEY: ENC[AES256_GCM,data:9lG05tGZKPo+X3+U78fyK5FzYc0/BAHzTiDXO0rq6KYXbjrLpTWi6eF4/wdAAbr7PeIunCDVLWv3,iv:k16M8KAXdZBFWNZCJyyaIgJkjxnK6byX3zLfFc2Pg6I=,tag:Jxf9ZWsHsVKtVizteAGl2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tatwwrxettyutu5zz3dmt349lqzjqfp8eheydzm76rqmqr5fu4usuj2cv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNVdvc0c4a2tsQ09oeVRY
            RVI5QnFGZTBlaklpa2ljeEZyK1hBTzB2a3h3CmJRRUJMazdvcm5SN0JydHVZdWNq
            WEtkUzFyT1pkZEtRN1NSa3NZSWxrSTgKLS0tIEtnVmRJclR1aWZnRUtUdHlHOVhJ
            TVdRbC9Qb3ZOUVJiN3QwQjh1ZFVONW8KNpf/f05iTddFhp9fn4LY/F1nebEP6Yn8
            l54JFwCvbxL4IFZpssIvKqwStzzVWPfuT8oq4i/ZI2j3B+GZ2AWH4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T03:42:09Z"
    mac: ENC[AES256_GCM,data:Tb76S2xLBcAVhOFamGNGPybHU5+BOw6YnDuSBkk7wbRZ2CE21H8HnHDXONIRIcNcbHjPpRb5gVFqi05rYQGHW/vSttfGQ8Vwxzo9nlbREaFGTShArlsTnX/wrqsR8gOSi2/7UbNPl/rwhY1/xH7iVC5Wpa89cTtEGJBROsbKSRk=,iv:0Y/1TD7v99/uYNAO1xBAPiMqQlsghar04H6iny6d1t4=,tag:vXl6aignjWMlff0ct+C9Jg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(^trusted|^secrets|^trustdinfo|^cluster|.[pP]assword|crt|key|^data$|^stringData))
    version: 3.7.3
