apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-infra
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd/aoa_infra/apps
    repoURL: https://github.com/VijayakumarRavi/argocd-homelab.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
