---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: kasten
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation: # perform remediation when helm install fails
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    eula:
      accept: true
    serviceAccount:
      create: true
    auth:
      tokenAuth:
        enabled: true
    global:
      persistence:
        storageClass: ceph-block
    clusterName: "${CLUSTER_NAME}"
    ingress:
      create: false
    grafana:
      enabled: false
    prometheus:
      server:
        enabled: false
