---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k10
  namespace: kasten-io
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${K10_DASHBOARD}`)
      kind: Rule
      services:
        - name: dashboardbff-svc
          port: 8000
  tls:
    certResolver: letsencrypt
