apiVersion: v1
kind: PersistentVolume
metadata:
  name: k10-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 10.0.3.124
    path: /mnt/storage/k8s_nfs/k10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k10-pvc
  namespace: kasten-io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName:  nfs
  resources:
    requests:
      storage: 100Mi
