---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-storage-k10-app
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/storage/k10/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
  dependsOn:
    - name: infrastructure-storage-rook-ceph-operator
    - name: infrastructure-storage-rook-ceph-cluster

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-storage-k10-config
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./kubernetes/infrastructure/storage/k10/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
  dependsOn:
    - name: infrastructure-storage-k10-app
