apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: pihole
    namespace: pihole
spec:
    interval: 5m
    chart:
        spec:
            chart: pihole
            version: 2.11.0
            sourceRef:
                kind: HelmRepository
                name: mojo2600-pihole-kubernetes
                namespace: pihole
            interval: 5m
    values:
        serviceDns:
            # was NodePort jjp
            type: LoadBalancer
            loadBalancerIP: 10.0.3.209
            # {}
            annotations:
                metallb.universe.tf/allow-shared-ip: pihole-svc
        serviceDhcp:
            # was true jjp
            enabled: false
        virtualHost: pihole-k8s.piccola.us
        ingress:
            enabled: false
        adminPassword: ENC[AES256_GCM,data:FLV8iS/j/C2iaalngVN/6Q==,iv:jmegZg5Qu5PQBUnSv/BTQwspv+Cuogvo8zfKYleoRas=,tag:eFzUNcEvHdN6opTzmmC3Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tatwwrxettyutu5zz3dmt349lqzjqfp8eheydzm76rqmqr5fu4usuj2cv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTkdpcVZ2Q1RZaVJKWjBL
            bEZtdGdLak9veUdHVTZOS1FoenMrYWczN2x3CnFTL2tiOXU3b2VqbWx5VElrN0U0
            b1dtazlWYWFZTjdBOFNJZFVJUHp1KzgKLS0tIHY5S0k3ZVRoQi9FN0ZJVDdRZG9U
            aXJnUFRZNG1VWlRtTUxjV2FqSkNDM0EKfMrNDTZi6bQp67/mMb13FYJgySMgHFHc
            Z7WIj4X1g+RIYv2BQ15tP505H4+0HQPER1OPwtaH68L/hoeFEZuBZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T20:51:21Z"
    mac: ENC[AES256_GCM,data:mqNS56UnT46BGY1nRxu+lM8RH0k1dotBY0bc9Oxzjn5yGS+VwXokRBviMyrDPMzUX7sd+CRGLIJqnGJ/JhgZxZrdKxM3OWHbc0XVYWHnNg/KpRpIqsoYUW+rcIZ0Ti7GsKd63HYHniScNV7pNR4aBU1TCL2U8d7xpdtbhFBmsCM=,iv:Zze7kWKw0KwoodBObEKzaeN6fG1hj7GLs2TlT5Xz+ak=,tag:rYXekF6RwfLea0Yz+HgJ3Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(^trusted|^secrets|^trustdinfo|^cluster|.[pP]assword|crt|key|^data$|^stringData))
    version: 3.7.3
