apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:DrJz0Z5rv6CWgDp7bTAskIXDfxEB/kEkYkzu4TMwdobP3WGekKWS3w==,iv:2U1At2wjFIqKYaZWUMIlY39X/CrqSLa3ATuowtl0zuk=,tag:3uCF0JvIpApHgh+GzXcHMw==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:U83FJ+Q=,iv:8x2VmBvlb2KJz5s/N/06RNTKhjrUXbtXpHUKIeUuRw0=,tag:4EjeUOs3zcHNUOwFVVnOFw==,type:str]
    K10_DASHBOARD: ENC[AES256_GCM,data:b5aHa6YlW3O2o9kvDwJv2eJe,iv:BfhrD1CS88cR7y+0eBftUwKDUb7tUka8KTjbBQMHQJg=,tag:daHcAxRRaVwIGaMN6PedjQ==,type:str]
    LE_EMAIL: ENC[AES256_GCM,data:+9ydTGW2BmHodA07VHX4e5T4Pkht/A==,iv:CAUl81QeWIf59sgWkeWvy1xUkz1RKCla2uQiaASc+xo=,tag:bbnNbZAskgQCZI0YXNHfPg==,type:str]
    PIHOLE_ADMINPASSWORD: ENC[AES256_GCM,data:Ja6S7wETjQ==,iv:Lc76+LvWqDyjzCFIOjL46zSxRAi9Q0FqKObapcdwank=,tag:TFvC7XBg3nYKpUPaq8j1Sw==,type:str]
    NGINX_INGRESS_SECRET_DOMAIN: ENC[AES256_GCM,data:dZMl6QvTDcKV9g==,iv:iekHMUzNtzWM0AkVKSZb0ceOpEQ+VXPmfW7+S7/yEAE=,tag:RKMJj4MCyQXJS6lW9yMArQ==,type:str]
    SECRET_NAS1: ENC[AES256_GCM,data:sWnaxRFIq+THflyJgGXxXTAk,iv:Ff10079tPW45lnu8/ycngfGXI/bwnkMLs/AJdWRf5mA=,tag:Sx63mde3c37O0h/7tudt2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tatwwrxettyutu5zz3dmt349lqzjqfp8eheydzm76rqmqr5fu4usuj2cv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTFdURTJMWDUzc2hrb1NW
            NUgzUnhQUEMxR25zVUNSVXphSWcrSnloVWtZCmswUm9qcUFlT0Nlb0IyV3gvNlVk
            U1MvcngwL1AxSjIrMXI5WTNyUVMzcWsKLS0tIHR2eFg1azJlak1xRDZUWWtHMkNO
            SXluR1dEU21BL0xaTXdNdjVmdkwxWFkKiAA76oewTlHTOk4adA2j0lq6j6O31UfF
            n1nY4dzfqAFdKnk5PSsKQ7L0nXGoNc/9JYhYOVmlF44mfDB1/E6qKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T22:25:19Z"
    mac: ENC[AES256_GCM,data:+wtcHSTvYHcM3DgdWUoPThJsB3A7evxjQCD0uCjDflYXjWqKHf5ZQqif5N83B1IbF5RLXKJEVRAf/wjDDGZxDNeASG0WSviCwOFsts05Q0tC5I65fSm0Kx/nHpQLRGXIT1QfYuZ8jPLBByPSzMpFIppqeofezSBfjVJ01GrNfvs=,iv:/3thhFwoOBxPatdKFhH/afu3JecvRsQNPoiNAf+Pel0=,tag:L4OUxx37UugBegpM9uRsFA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(^trusted|^secrets|^trustdinfo|^cluster|.[pP]assword|crt|key|^data$|^stringData))
    version: 3.7.3
