---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deploy
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: infrastructure
  interval: 10m0s
  path: ./kubernetes/deploy
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
