---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: joey-kustomization
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: deploy
  interval: 10m0s
  path: ./clusters/talos/apps/joey
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-age
