---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pihole-kustomization
  namespace: flux-system
spec:
  dependsOn:
    - name: deploy
  interval: 10m0s
  path: ./clusters/talos/apps/pihole
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
