apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.3.3
    helm:
      releaseName: argocd
      valuesObject:
        repoServer:
          volumes:
            - name: custom-tools
              emptyDir: {}
          initContainers:
            - name: download-tools # download argo vault plugin and copy it to custom-tools volume (we mount this in the repo server above)
              image: registry.access.redhat.com/ubi8
              env:
                - name: AVP_VERSION
                  value: 1.17.0
              command: [sh, -c]
              args:
                - >-
                  curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/) -o argocd-vault-plugin &&
                  chmod +x argocd-vault-plugin &&
                  mv argocd-vault-plugin /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-pruning-with-allow-empty-v18
    syncOptions:
      - CreateNamespace=true



# see https://github.com/argoproj/argo-cd/issues/10456 for details as to why this may be needed one day
# if it is needed value it in via valuesObject: configs.cm.resource.exclusions
# data:
#   resource.exclusions: |
#     - apiGroups:
#       - cilium.io
#       kinds:
#       - CiliumIdentity
#       clusters:
#       - "*"

# example of oob argocd/argocd-cm (configmap)
# data:
#   admin.enabled: "true"
#   application.instanceLabelKey: argocd.argoproj.io/instance
#   exec.enabled: "false"
#   server.rbac.log.enforce.enable: "false"
#   statusbadge.enabled: "false"
#   timeout.hard.reconciliation: 0s
#   timeout.reconciliation: 180s
#   url: https://argocd.example.com
