apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/compare-options: ServerSideDiff=true # https://github.com/argoproj/argo-cd/issues/19038
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.16.1 # 1.15.8
    helm:
      releaseName: cilium
      valuesObject:
        k8sServiceHost: localhost # talos' KubePrism
        k8sServicePort: 7445
        kubeProxyReplacement: true # use Cilium
        gatewayAPI:
          enabled: true
        bgpControlPlane:
          enabled: true
        l7Proxy: true
        bgp:
          announce:
            loadbalancerIP: true
        ipam:
          mode: kubernetes
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        securityContext:
          capabilities:
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
