apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: goldilocks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: goldilocks
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: 9.0.0
    helm:
      releaseName: goldilocks
      valuesObject:

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: goldilocks-route
  namespace: goldilocks
spec:
  hostnames:
    - goldilocks-k8s.<path:cluster-secrets:cluster-secrets#domain>
  parentRefs:
  - name: internal
    namespace: gateway
  rules:
  - backendRefs:
    - name: goldilocks-dashboard
      port: 80

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: goldilocks # for cert-manager to access 'cloudflare-api-token-secret' it must exists in cert-manager's ns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token-secret # this is the name of the native k8s secret to create
      remoteRef:
        key: cluster-secrets # this is the title of the item in 1password
        property: cloudflare-token # this is the name of the property on the 1password item
