# Possible values: https://github.com/stakater/pihole/blob/master/deployments/kubernetes/chart/pihole/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    chart: pihole
    targetRevision: 2.26.1
    helm:
      releaseName: pihole
      valuesObject:
        DNS1: "10.0.3.24"
        adminPassword: <path:cluster-secrets:cluster-secrets#pihole-admin-password>
        serviceDns:
          # this is true as the cilium "io.cilium/lb-ipam-sharing-key" svc annotation does not work on services with different ports, that said create a single dual protocol service
          mixedService: true
          type: LoadBalancer # was NodePort jjp
          annotations:
            # use last ip from 10.0.5.208/28
            io.cilium/lb-ipam-ips: 10.0.5.222
            # io.cilium/lb-ipam-sharing-key: pihole
        serviceDhcp:
          enabled: false # was true jjp
        virtualHost: pihole-k8s.<path:cluster-secrets:cluster-secrets#domain>
        # persistentVolumeClaim:
        #   enabled: true
        #   existingClaim: pihole
        ingress:
          enabled: false
  destination:
    name: in-cluster
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
