---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-ceph-pvc
  namespace: pihole
  # labels:
  #   triliovault.trilio.io/backup: "true"
  #   kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
