---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-test
  namespace: cluster-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: my-secret # this is the name of the native k8s secret
    remoteRef:
      key: my-secret # this is the title of the item in 1password
      property: sec_a
