apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.15.1
    helm:
      releaseName: rook-ceph
      valuesObject:
        crds:
          enabled: true
        csi:
          kubeletDirPath: /var/lib/kubelet
          enableCSIHostNetwork: true
          pluginTolerations:
            - effect: "NoExecute"
              operator: "Exists"
            - effect: "NoSchedule"
              operator: "Exists"
        # monitoring:
        #   enabled: true
        resources:
          requests:
            cpu: 109m
            memory: 204M
          limits:
            memory: 500M
  destination:
    name: in-cluster
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

